function openPopup() {
    document.getElementById("popup").style.display = "flex";
}

function closePopup() {
    document.getElementById("popup").style.display = "none";
}
function checkMultiplePhrases() {
    let userInput = document.getElementById("userInput").value.toLowerCase().trim();
    let messageBox = document.getElementById("message");

    let responses = {
        "הלל": "יצאתי מדעתי, תכף אשוב",
        "הלל צור": "יצאתי מדעתי, תכף אשוב",
        "hillel": "putting the I in teamwork",
        "רננה": "you can't know that",
        "איתן": "ועכשיו?",
        "אמא": "gutten you!",
        "bill cipher": "reality is an illusion! the universe is a hologram! buy gold! byeeeeeeee",
        "alastor": "you're never fully dressed without a smile",
        "the dragon warrior": "skadoosh!",
        "gandalf": "you! cannot! paaaaaaas!",
        "darth vader": "no, i am your father",
        "terminator": "I'll be back",
        "dory": "just keep swimming",
        "vilhelm": "aaaaaaaaah!",
        "luke skywalker": "noooooo!",
        "buzz lightyear": "to infinity, and beyond!",
        "the godfather": "I'm gonna make him an offer he can't refuse",
        "don vito": "I'm gonna make him an offer he can't refuse",
        "joker": "Why so serious?",
        "dorothy": "there's no place like home",
        "master oogway": "Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present",
        "edna mode": "I never look back, darling. It distracts from the now.",
        "kronk": "Oh, right. The poison. The poison for Kuzco, the poison chosen especially to kill Kuzco, Kuzco's poison. That poison?",
        "cheshire cat": "If you don't know where you are going, any road can take you there",
        "the cheshire cat": "If you don't know where you are going, any road can take you there",
        "rafiki": "Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it",
        "homer": "Here's to alcohol: the cause of, and solution to, all of life's problems",
        "homer simpson": "If you don't like your job, you don't strike. You just go in every day and do it really half-assed",
        "Frodo": "I will take the Ring, though I do not know the way",
        "the mad hatter": "We're all mad here",       
        "dumbledore": "It does not do to dwell on dreams and forget to live",
        "albus dumbledore": "To the well-organised mind, death is but the next great adventure",
        "bart simpson": "Soul? Come on, Milhouse, there is no such thing as a soul. It's just something they made up to scare kids..",
        "lisa simpson": "Better to remain silent and be thought a fool than to open your mouth and remove all doubt",
        "marge simpson": "I don't hate you for failing. I love you for trying",
        "idniana jones": "it belongs in a museum",
        "james bond": "my name is Bond. James Bond",
        "sirius black": "We've all got both light and dark inside us. What matters is the part we choose to act on. That's who we really are",
        "Albus Percival Wulfric Brian Dumbledore": "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends",
        "rubeus hagrid": "What’s coming will come, and we’ll meet it when it does",
        "hagrid": "What’s coming will come, and we’ll meet it when it does",
        "harry": "there's no need to call me 'sir' professor",
        "harry potter": "there's no need to call me 'sir' professor",
        "snape": "I can teach you how to bewitch the mind and ensnare the senses. I can teach you how to bottle fame, brew glory, and even put a stopper in death",
        "severus snape": "I can teach you how to bewitch the mind and ensnare the senses. I can teach you how to bottle fame, brew glory, and even put a stopper in death",
        "hermione": "Now, if you two don't mind, I'm going to bed. Before either of you come up with another clever idea to get us killed—or worse, expelled",
        "hermione granger": "Now, if you two don't mind, I'm going to bed. Before either of you come up with another clever idea to get us killed—or worse, expelled",
        "ron": "From now on, I don't care if my tea leaves spell, 'Die, Ron, die,' I'm chucking them in the bin",
        "ron weasley": "Bloody hell",
        "Ronald Bilius Weasley": "Why spiders? Why couldn't it be 'follow the butterflies'?",
        "po": "My old enemy... Stairs",
        "george and fred": "We know our names are Gred and Forge",
        "george weasley": "Saintlike. You see... I'm HOLEY, Fred.",
        "fred weasley": "The whole wide world of ear-related humor and you go for 'I'm holy'? That's pathetic",
        "lord voldemort": "Harry Potter, the Boy Who Lived... come to die",
        "tom riddle": "Voldemort is my past, present, and future",
        "voldemort": "There is no good and evil. There is only power, and those too weak to seek it!",
        "neville longbottom": "I won't let you do it, I'll — I'll fight you!",
        "mcgonagall": "You look in excellent health to me, Potter, so you will excuse me if I don’t let you off homework today. I assure you that if you die, you need not hand it in",
        "minerva mcgonagall": "Have a biscuit, Potter",
        "professor mcgonagall": "Perhaps it would be more useful if I were to Transfigure yourself and Mr Potter into a pocket watch? That way one of you might be on time",
        "draco": "Goyle, Honestly, if you were any slower, you'd be going backward",
        "malfoy": "Famous Harry Potter,Can't even go to a bookshop without making the front page",
        "draco malfoy": "Longbottom, if brains were gold, you'd be poorer than Weasley, and that's saying something",
        "remus lupin": "Eat. You'll feel better",
        "lupin": "Eat. You'll feel better",
        "batman": "I. Am. Batman",
        "groot": "I am groot",
        "thanos": "I am inevitable",
        "jack sparrow": "why is the rum gone?",
        "captain jack sparrow": "Me? I'm dishonest. And a dishonest man you can always trust to be dishonest. Honestly. It's the honest ones you want to watch out for, because you can never predict when they're going to do something incredibly... stupid",
        "yoda": "Choose or choose not. There is no try",
        "master yoda": "Patience you must have my young Padawan",
        "marty mcfly": "No wonder your president has to be an actor. He's gotta look good on television.",
        "bilbo baggins": "It's a dangerous business, Frodo, going out your door",
        "shrek": "better in than out I always say",
        "donkey": "I like that boulder. That is a nice boulder",
        "dobby": "Dobby never meant to kill. He only meant to maim, or seriously injure",
        "mickey mouse": "see ya real soon",
        "spiderman": "I can't be a friendly neighborhood Spider-Man if there's no neighborhood",
        "bugs bunny": "Of course, as you know, society is made up of—uh—well, mostly of people.",
        "bugs": "I knew I shoulda made a left turn at Albuquerque",
        "winnie the pooh": "Some people care too much. I think it's called love",
        "han solo": "Never tell me the odds!",
        "sherrif woody": "Reach for the sky!",
         "woody": "Reach for the sky!",
         "woody allen": "I'm not afraid of death; I just don't want to be there when it happens",
         "charlie":"I've developed a new philosophy. I only dread one day at a time",
         "charlie brown":"Sometimes I lie awake at night, and I ask, 'Where have I gone wrong?' Then a voice says to me, 'This is going to take more than one night",
         "chuck":"In the book of life, the answers aren't in the back",
         "brown":"Don't worry about the world coming to an end today. It's already tomorrow in Australia",
         "molly weasley":"If you put another toe out of line, we'll bring you straight home!",
         "arthur weasley":"Tell me, what exactly is the function of a rubber duck?",
         "arthur":"Never trust anything that can think for itself if you can't see where it keeps its brain!",
         "mr peabody":"I have a deep regard for you as well, Sherman",
         "alastor moody":"Constant vigilance!",
         "mad eye moody":"I'm here because Dumbledore asked me. End of story, goodbye, the end!",
         "moody":"And hear across classrooms!",
         "uncle vernon":"We've raised you since you were a baby. We've given you the food at our table, you even have Dudley's second bedroom, clearly out of the goodness of our hearts",
         "lord farquaad":"Some of you may die, but it's a sacrifice I am willing to make",
         "mike wazowski":"First of all, it's 'cretin.' If you're gonna threaten me, do it properly",
         "mike":"your stunned silence is very reassuring",
         "james p sullivan":"Did you lose weight? Or a limb?",
         "sully":"Hey, Mike, this might sound crazy but I don't think that kid's dangerous.",
         "sid":"From now on, you'll have to refer to me as 'Sid, Lord of the Flame'",
         "sid the sloth":"You did it, buddy, you kicked water's butt!",
         "manny":"Diego, spit that out. You don't know where it's been (referring to Sid)",
         "manfred":"So you got three melons? (referring to the dodos' supply for the ice age)",
         "diego":"I don't eat junk food (referring to sid's fear that he would eat him)",
         "manny the mammoth":"If you find a mate in life, you should be loyal. In your case, grateful (to sid)",
         "bruce the shark":"I am a nice shark, not a mindless eating machine. If I am to change this image, I must first change myself. Fish are friends, not food!",
         "marlin":"You trust Becky? Becky's eating a cup!",
         "edna":"no capes!",
         "mr incredible":"No matter how many times you save the world, it always manages to get back in jeopardy again. Sometimes I just want it to stay saved!",
         "mushu":"Dishonor! Dishonor on your whole family! Make a note of this. Dishonor on you!",
         "king julian":"Welcome, giant pansies. Please feel free to bask in my glow",
         "mort":"Oh, yayyyy! I'm a sacrifice!",
         "skipper":"smile and wave boys, smile and wave",
         "alex the lion":"You maniac! You burned it up! Darn you! Darn you all to heck!",
         "melman":"Ahhhhh! Nature! It's all over me! Get it off!",
         "alex":"Be sure to visit my web site. 24-hour webcam. Watch me sleep.",
         "melman":"They are so cute from a reasonable distance",
         "oscar wilde":"Be yourself; everyone else is already taken",
         "oscar":"I am so clever that sometimes I don't understand a single word of what I am saying",
         "andre gide":"It is better to be hated for what you are than to be loved for what you are not",
         "allen saunders":"Life is what happens to us while we are making other plans",
         "thomas edison":"I have not failed. I've just found 10,000 ways that won't work",
         "douglas adams":"I may not have gone where I intended to go, but I think I have ended up where I needed to be",
         "groucho marx":"Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read",
         "steve martin":"A day without sunshine is like, you know, night",
         "mark twain":"Never put off till tomorrow what may be done day after tomorrow just as well",
         "nietzsche":"That which does not kill us makes us stronger",
         "ralph waldo emerson":"For every minute you are angry you lose sixty seconds of happiness",
         "adams":"I love deadlines. I love the whooshing noise they make as they go by",
         "friedrich nietzsche":"I'm not upset that you lied to me, I'm upset that from now on I can't believe you",
         "albert einstein":"If you can't explain it to a six year old, you don't understand it yourself",
         "garrison keillor":"Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car",
         "pablo piccasos":"Everything you can imagine is real",
         "anais nin":"We don't see things as they are, we see them as we are",
         "robert heinlein":"Women and cats will do as they please, and men and dogs should relax and get used to the idea",
         "dr seuss":"Sometimes the questions are complicated and the answers are simple",
         "george bernard shaw":"Life isn't about finding yourself. Life is about creating yourself",
         "charles schulz":"All you need is love. But a little chocolate now and then doesn't hurt",
         "jim henson":"Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye",
         "einstein":"Logic will get you from A to Z; imagination will get you everywhere",
         "paul terry":"Whenever I feel the need to exercise, I lie down until it goes away",
         "abraham lincoln":"Folks are usually about as happy as they make their minds up to be",
         "ernest hemingway":"There is no friend as loyal as a book",
         "bob marley":"One good thing about music, when it hits you, you feel no pain",
         "groucho":"I find television very educating. Every time somebody turns on the set, I go into the other room and read a book",
         "helen keller":"When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us",
         "charles bukowski":"Some people never go crazy. What truly horrible lives they must lead",
         "anais":"Love never dies a natural death. It dies because we don't know how to replenish its source. It dies of blindness and errors and betrayals. It dies of illness and wounds; it dies of weariness, of witherings, of tarnishings",
         "doofenshmirtz":"Wow, if I had a nickel for every time I was doomed by a puppet, I'd have two nickels - which isn't a lot, but it's weird that it happened twice",
         "dr heinz doofenshmirtz":" I never built an Amnesianator! I think I'd remember building something like THAT",
         "dr doofenshmirtz":"Anyway, I don't know why you're being so uncooperative. All I'm asking you to do is make my machine work so I can invade and conquer your world and enslave your loved ones",
         "alexander dumas fils":"The difference between genius and stupidity is: genius has its limits",
         "terry pratchett":"The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it",
         "bill watterson":"Reality continues to ruin my life",
         "walter miller jr":"You don’t have a soul, Doctor. You are a soul. You have a body, temporarily",
         "marthe troly-curtin":"Time you enjoy wasting is not wasted time",
         "benjamin franklin wade":"Go to heaven for the climate and hell for the company",
         "george carlin":"The reason I talk to myself is because I’m the only one whose answers I accept",
         "hemingway":"There is nothing to writing. All you do is sit down at a typewriter and bleed.",
         "twain":"′Classic′ - a book which people praise and don't read",
         "fields":"I am free of all prejudice. I hate everyone equally",
         "schulz":"I love mankind ... it's people I can't stand!!",
         "mark":"I have never let my schooling interfere with my education",
         "c.s. lewis":"Some day you will be old enough to start reading fairy tales again",
         "john green":"The marks humans leave are too often scars",
         "j.m. barrie":"To die will be an awfully big adventure",
         "truth":"A lie can travel half way around the world while the truth is putting on its shoes",
         "isaac asimov":"The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom",
         "roald dahl":"Those who don't believe in magic will never find it",
         "harper lee":"until I feared I would lose it, I never loved to read. One does not love breathing",
         "mahatma gandhi":"An eye for an eye will only make the whole world blind",
         "bukowski":" -Do you hate people? I- don't hate them...I just feel better when they're not around",


    };

    if (responses[userInput]) {
        messageBox.innerHTML = responses[userInput];
        messageBox.style.color = " cyan";
    } else {
        messageBox.innerHTML = " personality was not yet fed into the database.";
        messageBox.style.color = "red";
    }
}